// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaAGqL1xDFmsvs5hFPMLcwj1WzsqvqfDU',
    appId: '1:938278576687:web:f19353adf201fb6821dcda',
    messagingSenderId: '938278576687',
    projectId: 'chatnow-dbd3f',
    authDomain: 'chatnow-dbd3f.firebaseapp.com',
    storageBucket: 'chatnow-dbd3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDelx_uGHQeXXHRf463LJoh1AlzOs6kXQM',
    appId: '1:938278576687:android:251a494fcb74150721dcda',
    messagingSenderId: '938278576687',
    projectId: 'chatnow-dbd3f',
    storageBucket: 'chatnow-dbd3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIvwtS3JQXvGvNPHL9_m7QBYj77DgZVc',
    appId: '1:938278576687:ios:29b825e7ced4429121dcda',
    messagingSenderId: '938278576687',
    projectId: 'chatnow-dbd3f',
    storageBucket: 'chatnow-dbd3f.appspot.com',
    iosClientId: '938278576687-98gku7cesqihdmd4kljqrgilalqjum9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjIvwtS3JQXvGvNPHL9_m7QBYj77DgZVc',
    appId: '1:938278576687:ios:29b825e7ced4429121dcda',
    messagingSenderId: '938278576687',
    projectId: 'chatnow-dbd3f',
    storageBucket: 'chatnow-dbd3f.appspot.com',
    iosClientId: '938278576687-98gku7cesqihdmd4kljqrgilalqjum9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatnow',
  );
}
